spring.application.name=focus
spring.datasource.url=jdbc:postgresql://localhost:5432/focus
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#set dimensione immagini
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.cloud.gcp.credentials.location=glowing-hearth-480910-r6-886a6d258cba.json
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
#Hibernate
spring.jpa.hibernate.ddl-auto=update
#Real-Time
spring.threads.virtual.enabled=true
#Cloudinary
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}

cloudinary.api_secret=${CLOUDINARY_SECRET}

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh_expiration=${JWT_REFRESH_EXPIRATION}